spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common_issue_and_solution
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true