spring:
  datasource:
    url: jdbc:mysql://localhost:3306/common-issue-and-solution
    username: root
    password: mypa11
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true